[package]
name = "rustenger-shared"
version = "0.0.0"
authors = ["Aitzhanov Ivan <aitvann@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
arrayvec = { version = "0.5", features = ["serde"] }
